version: 2.1

commands:
  set_up_dependencies:
    steps:
      - run:
          name: "Install pnpm"
          command: npm install -g pnpm
      - restore_cache:
          keys:
            - pnpm-v1-{{ checksum "pnpm-lock.yaml" }}
            - pnpm-v1-
      - run:
          name: "Install dependencies"
          command: pnpm install
      - run:
          name: "Check that install didn't create diff"
          command: git diff -s --exit-code pnpm-lock.yaml
      - save_cache:
          paths:
            - node_modules
            - apps/documentation/node_modules
            - apps/web/node_modules
            - packages/eslint-config-custom/node_modules
            - packages/prettier-config-custom/node_modules
            - packages/tsconfig/node_modules
            - packages/ui/node_modules
            - packages/use-url-search-param/node_modules
          key: pnpm-v1-{{ checksum "pnpm-lock.yaml" }}

jobs:
  build:
    docker:
      - image: cimg/node:16.16
    steps:
      - checkout
      - set_up_dependencies
      - run:
          name: "Build"
          command: pnpm run build
  typecheck:
    docker:
      - image: cimg/node:16.16
    steps:
      - checkout
      - set_up_dependencies
      - run:
          name: "Check types"
          command: pnpm run typecheck
  test:
    docker:
      - image: cimg/node:16.16
    steps:
      - checkout
      - set_up_dependencies
      - run:
          name: "Run tests"
          command: pnpm run test
  lint_format_license:
    docker:
      - image: cimg/node:16.16
    steps:
      - checkout
      - set_up_dependencies
      - run:
          name: "Lint"
          command: pnpm run lint
      - run:
          name: "Prettier"
          command: pnpm run prettier
      - run:
          name: "License checker"
          command: pnpm run license-checker

workflows:
  test:
    jobs:
      - build
      - typecheck
      - lint_format_license